CREATE TABLE IF NOT EXISTS domain_lists (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  source_filename TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS domains (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  domain_list INTEGER NOT NULL,
  rank INTEGER NOT NULL,
  domain TEXT NOT NULL,

  FOREIGN KEY (domain_list) REFERENCES domain_lists (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS analyses (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  type TEXT,
  domain_list INTEGER NOT NULL,

  FOREIGN KEY (domain_list) REFERENCES domain_lists (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS analysis_results (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  analysis INTEGER NOT NULL,
  domain INTEGER NOT NULL,
  detail TEXT NOT NULL,
  start_time INTEGER,
  end_time INTEGER,

  UNIQUE (analysis, domain),
  FOREIGN KEY (analysis) REFERENCES analyses (id) ON DELETE CASCADE,
  FOREIGN KEY (domain) REFERENCES domains (id) ON DELETE CASCADE
);
